#!/bin/sh

autoload -U zgitinit && zgitinit

prompt_tt_setup() {
	export PROMPT='%m%b%f:%F{blue}%1~%f$(prompt_tt_vcs) %(!.#.%%) '
	export RPROMPT=''
}

prompt_tt_vcs() {
	zgit_isgit && echo "$(prompt_tt_git)"
}

prompt_tt_git() {
	zgit_isgit || return

	echo -n '('
	echo -n "$(zgit_head)"

	if zgit_inworktree; then
		echo -n "$(zgit_isindexclean || print 'n')"
		echo -n '%F{magenta}'
		echo -n "$(zgit_isworktreeclean || print '!')"
		echo -n "$(zgit_hasunmerged && print '*')"
		echo -n "$(zgit_hasuntracked && print '?')"
		echo -n '%f'
	fi

	echo -n ')'
}

prompt_tt_setup "$@"
