#!/bin/sh

function title {
	case $TERM in
		screen*)
			print -Pn "\ek$1:q\e\\"
		;;
		xterm*)
			print -Pn "\e]1;$1:q\a" # tab title
			print -Pn "\e]2;$2:q\a" # window title
		;;
	esac
}

function title_precmd {
  title '%1~%(1C./.)' '%n@%m:%~'
}

function title_preexec {
	setopt extended_glob
	title "${1[(wr)^(*=*|sudo|ssh|-*)]}" "$2"
}

add-zsh-hook precmd title_precmd
add-zsh-hook preexec title_preexec
